services:
  - type: web
    name: the-sweet-escape-crm
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SECRET_KEY
        sync: false
      - key: SUPABASE_DB_URL
        sync: false